name: Compila y genera PDF
on: 
  push:

jobs:
  compila:
    runs-on: ubuntu-latest

    steps:
      - name: Saludar
        uses: richardortizp/url-validator@v1.1
        with:
          who-to-greet: 'Ricardo'
  
      - name: Tener copia local del repositorio
        uses: actions/checkout@v4.2.2

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Instalar dependencias
        run: dotnet restore

      - name: Copilar
        run: dotnet build --no-restore

  crear-pdf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_dir: docs
          output_dir: pdfs
          # Default is true, can set to false to only get PDF files
          build_html: true
      - uses: actions/upload-artifact@v4
        with:
          name: docs
          path: pdfs
